import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
import PolicyPanel from './PolicyPanel';
type Metrics={model_calls:number|null;tool_calls:number|null;latency_ms:number|null;tokens?:number|null};
type Run={order_id?:string;run_id:string;status:string;mode:string;reason_code?:string;metrics:Metrics;quote?:{amount_krw:number};routing?:unknown;oracle?:unknown};
type Trace={seq:number;kind:string;payload:string;[key:string]:unknown};
type Workflow={id:string;state:string;artifact_hash:string;artifact:{source_mode:string;support_count:number;source_trace_ids:string[];[key:string]:unknown};report:null|{count:number;passed:boolean;boundary_checks?:unknown[]}};
type Summary={n:number;passed:number;unsafe:number;model_calls:number;p50_ms:number;p95_ms:number};
type Report={id:string;mode:string;summary:Record<string,Summary>};
type Health={live_verified:boolean;key_configured:boolean;nat_verified:boolean;openshell_verified:boolean};
function App(){
 const [token,setToken]=useState(''),[session,setSession]=useState(''),[message,setMessage]=useState('운영자 토큰을 연결하면 수집·승인·활성화가 가능합니다.'),[busy,setBusy]=useState(false);
 const [order,setOrder]=useState('order-001'),[text,setText]=useState(''),[mode,setMode]=useState('mock'),[route,setRoute]=useState('auto');
 const [result,setResult]=useState<Run|null>(null),[events,setEvents]=useState<Trace[]>([]),[flows,setFlows]=useState<Workflow[]>([]),[reports,setReports]=useState<Report[]>([]),[health,setHealth]=useState<Health|null>(null);
 const [bound,setBound]=useState({order:'',mode:'mock',route:'auto'});
 async function api<T>(path:string,body?:unknown):Promise<T>{const response=await fetch(path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(token?{'X-Operator-Session':token}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});const value=await response.json();if(!response.ok)throw Error(typeof value.detail==='string'?value.detail:value.message||value.error||JSON.stringify(value.detail));return value as T;}
 async function refresh(){const [h,w,r]=await Promise.all([api<Health>('/health'),api<Workflow[]>('/api/workflows'),api<Report[]>('/api/evaluations')]);setHealth(h);setFlows(w);setReports(r);}
 useEffect(()=>{refresh().catch(e=>setMessage(String(e)));},[]);
 async function act(fn:()=>Promise<void>){if(busy)return;setBusy(true);setMessage('처리 중입니다…');try{await fn();}catch(e){setMessage('처리하지 못했습니다: '+String(e));}finally{setBusy(false);}}
 async function run(approval?:string){
   const selected=approval?bound:{order,mode,route};setBound(selected);setEvents([]);setResult(null);
   const started=await api<{run_id:string}>('/api/runs',{order_id:selected.order||null,...(!approval&&text?{text}:{}),mode:selected.mode,route:selected.route,approval_id:approval||null,request_id:crypto.randomUUID()});
   setMessage('에이전트 실행 중 · '+started.run_id);
   await new Promise<void>((resolve,reject)=>{const stream=new EventSource(`/api/runs/${started.run_id}/events`);const timer=setTimeout(()=>{stream.close();reject(Error('연결 시간이 초과되었습니다. 실행 ID로 상태를 확인하세요: '+started.run_id));},125000);
    stream.addEventListener('trace',event=>{const row=JSON.parse((event as MessageEvent).data) as Trace;setEvents(old=>old.some(x=>x.seq===row.seq)?old:[...old,row]);});
    stream.addEventListener('done',event=>{clearTimeout(timer);stream.close();const value=JSON.parse((event as MessageEvent).data) as Run;setResult(value);if(value.order_id)setBound({...selected,order:value.order_id});setMessage('실행 완료: '+value.status);resolve();});
    stream.onerror=()=>setMessage('진행 스트림 재연결 중 · '+started.run_id);
   });await refresh();
 }
 async function scenario(kind:string){const r=await api<{order_id:string}>('/api/demo/new-order',{kind});setOrder(r.order_id);setText('');setMessage('새 합성 주문 생성: '+r.order_id);}
 async function approve(){if(!result?.quote)return;const approval=await api<{approval_id:string}>('/api/approvals',{order_id:bound.order,amount_krw:result.quote.amount_krw});await run(approval.approval_id);}
 function download(){const blob=new Blob([events.map(e=>JSON.stringify(e)).join('\n')+'\n'],{type:'application/x-ndjson'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=(result?.run_id||'trace')+'.jsonl';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const report=reports[0];
 return <><aside><a className="brand" href="#">▧ <b>SkillForge</b></a><span className="eyebrow">AGENT OPERATIONS</span><nav><a href="#run">01 실행 콘솔</a><a href="#workflow">02 워크플로 랩</a><a href="#evaluation">03 평가 리포트</a></nav><div className="aside-foot"><span className="dot"/> Synthetic commerce sandbox<br/><small>실제 결제는 발생하지 않습니다.</small></div></aside><main>
 <header><span>WORKSPACE / REFUND OPERATIONS</span><span className="badge">{health?.live_verified?'NVIDIA LIVE 검증 완료':health?.key_configured?'LIVE 준비됨':'MOCK 환경'}</span></header>
 <section className="hero"><div><span className="eyebrow green">TRACE → VERIFY → REUSE</span><h1>검증된 자동화도,<br/>정책이 바뀌면 다시 확인.</h1><p>실행 기록을 재사용 가능한 절차로 바꾸고, 정책 변경의 영향을 비교하세요.<br/>모든 실행은 동일한 정책 게이트웨이를 통과합니다.</p></div><div className="hero-note"><b>06</b><span>공통 업무 도구</span><small>주문 → 반품 → 정책 → 견적 → 환불 → 검증</small></div></section>
 <div id="notice" role="status" aria-live="polite">{message}</div><section className="session"><label htmlFor="session">운영자 세션</label><input id="session" type="password" autoComplete="off" value={session} onChange={e=>setSession(e.target.value)} placeholder="로컬 토큰 · 메모리에만 유지"/><button disabled={busy} onClick={()=>{setToken(session.trim());setSession('');setMessage('토큰을 연결했습니다. 운영 요청에서 서버 검증합니다.');}}>연결</button><span>{token?'토큰 입력됨':'연결 전'} · NAT {health?.nat_verified?'검증됨':'미검증'} · OpenShell 미검증</span></section>
 <section id="run"><div className="section-head"><div><span className="eyebrow">01 / EXECUTE</span><h2>실행 콘솔</h2></div><span className="badge">정책 검사 · 원자적 거래 · 독립 oracle</span></div><div className="columns"><article><h3>새 환불 요청</h3><div className="scenarios">{[['normal','정상 반품'],['high','고액 승인'],['unreceived','미수령 차단'],['policy-change','35만원 반품']].map(([k,label])=><button key={k} disabled={busy} onClick={()=>act(()=>scenario(k))}>{label}</button>)}</div><label htmlFor="order">주문 ID</label><input id="order" value={order} onChange={e=>setOrder(e.target.value)} disabled={busy}/><label htmlFor="request-text">자연어 요청 (선택)</label><input id="request-text" value={text} onChange={e=>setText(e.target.value)} placeholder="예: order-001 반품한 상품 환불해주세요" disabled={busy}/><div className="two"><div><label htmlFor="mode">에이전트</label><select id="mode" value={mode} disabled={busy} onChange={e=>setMode(e.target.value)}><option value="mock">Mock · 스크립트 실행</option><option value="live">Live · NVIDIA Nemotron</option></select></div><div><label htmlFor="route">실행 경로</label><select id="route" value={route} disabled={busy} onChange={e=>setRoute(e.target.value)}><option value="auto">검증 워크플로 우선</option><option value="react">에이전트 직접 실행</option></select></div></div><button className="primary wide" disabled={busy} onClick={()=>act(()=>run())}>{busy?'실행 중…':'환불 처리 실행 →'}</button>{result?.status==='AWAITING_APPROVAL'&&<div id="approval"><p>고액 환불: 운영자 승인 후 재개가 필요합니다.</p><button disabled={busy} onClick={()=>act(approve)}>승인 발급 및 재개</button></div>}{result?.status==='NEEDS_RECONCILIATION'&&<div><p>이 주문은 추가 쓰기가 보류되었습니다. 운영자가 DB 상태를 확인해야 합니다.</p><button disabled={busy} onClick={()=>act(async()=>{const r=await api<{state:string}>(`/api/reconciliations/${bound.order}/resolve`,{});setMessage(`상태 확인 완료: ${r.state}. 환불을 재시도하지 않았습니다.`);})}>상태 확인 및 보류 해제</button></div>}<p className="muted">자연어 Live 요청은 의도 추출에도 모델을 호출합니다. 모델 직접 실행을 확인하려면 실행 경로를 바꾸세요.</p></article><article><h3>최근 실행</h3>{result?<><div className="result-status">{result.status}</div><p className="muted">{result.mode} · {result.run_id}</p><p>{result.reason_code||'결과 및 DB 상태 검증 완료'}</p><div className="metrics">{[['model_calls','실제 모델 호출'],['tool_calls','도구 호출'],['latency_ms','실측 시간 (ms)']].map(([k,l])=><div className="metric" key={k}><b>{result.metrics?.[k as keyof Metrics]??'미측정'}</b><span>{l}</span></div>)}</div><details><summary>실행 결과 JSON</summary><pre>{JSON.stringify(result,null,2)}</pre></details></>:<p className="empty">{busy?'아래 타임라인에서 진행 상태를 확인하세요.':'실행 후 상태와 실측 지표가 표시됩니다.'}</p>}</article></div>
 <article className="trace"><div className="section-head"><h3>실시간 감사 타임라인</h3><button disabled={!events.length} onClick={download}>JSONL 다운로드</button></div>{events.length?events.map(e=><details className="event" key={e.seq}><summary><span>{String(e.seq).padStart(2,'0')}</span>{e.kind}</summary><pre>{JSON.stringify(e,null,2)}</pre></details>):<p className="empty">공개된 도구 호출·정책 판정·거래 결과를 표시합니다.</p>}</article></section>
 <section id="workflow"><div className="section-head"><div><span className="eyebrow">02 / COMPILE & GOVERN</span><h2>정책 변화에 대응하는 워크플로</h2></div></div><PolicyPanel flows={flows} busy={busy} api={api} act={act} refresh={refresh} message={setMessage}/><article><div className="pipeline"><div><b>01</b><strong>기록 수집</strong><p>Discovery 30건<br/>Mock 출처 명시</p><button disabled={busy} onClick={()=>act(async()=>{const r=await api<{new_runs:string[]}>('/api/demo/discover',{});setMessage(`Mock ${r.new_runs.length}건 수집 완료`);})}>기록 수집</button></div><div><b>02</b><strong>후보 생성</strong><p>독립 성공 기록 5건 이상<br/>정확한 도구·참조 일치</p><button disabled={busy} onClick={()=>act(async()=>{await api('/api/candidates',{});await refresh();setMessage('후보 생성 완료. 검증을 진행하세요.');})}>후보 생성</button></div><div><b>03</b><strong>분리 검증</strong><p>Validation 30건<br/>독립 DB oracle 판정</p></div><div><b>04</b><strong>운영자 활성화</strong><p>해시·정책 버전 확인<br/>변경 시 자동 무효화</p></div></div></article><div className="workflow-list">{flows.map(w=><article className="workflow" key={w.id}><div><strong>{w.id} · {w.state}</strong><p>출처 {w.artifact.source_mode} · 독립 성공 {w.artifact.support_count}건 · 검증 {w.report?w.report.count+'건 + 경계 '+(w.report.boundary_checks?.length||0)+'건 '+(w.report.passed?'통과':'실패'):'대기'}</p>{typeof w.artifact.parent_artifact_hash === 'string' && <p>정책 재검증 버전 · 실행 출처는 이전 정책에서 수집했습니다.</p>}<details><summary>출처 기록 · 실행 절차 · 버전</summary><pre>{JSON.stringify(w.artifact,null,2)}</pre><div>{w.artifact.source_trace_ids.map(id=><button key={id} onClick={()=>act(async()=>{setEvents((await api<{events:Trace[]}>(`/api/runs/${id}/events`)).events);setMessage('출처 trace 로드: '+id);document.getElementById('run')?.scrollIntoView();})}>{id}</button>)}</div></details></div><div>{w.state==='CANDIDATE'&&<button disabled={busy} onClick={()=>act(async()=>{await api(`/api/workflows/${w.id}/verify`,{});await refresh();setMessage('검증 결과 갱신 완료');})}>분리·경계 검증</button>}{w.state==='VERIFIED'&&<button disabled={busy} className="primary" onClick={()=>act(async()=>{await api(`/api/workflows/${w.id}/activate`,{expected_hash:w.artifact_hash});await refresh();setMessage('활성화 완료');})}>활성화</button>}{w.state==='ACTIVE'&&<button disabled={busy} onClick={()=>act(async()=>{await api(`/api/workflows/${w.id}/disable`,{});await refresh();setMessage('워크플로를 중지했습니다.');})}>중지</button>}</div></article>)}{!flows.length&&<p className="muted">후보가 없습니다. 먼저 기록을 수집하세요.</p>}</div></section>
 <section id="evaluation"><div className="section-head"><div><span className="eyebrow">03 / MEASURE</span><h2>같은 조건, 세 가지 실행 경로</h2></div><button disabled={busy} className="primary" onClick={()=>act(async()=>{await api('/api/evaluations',{});await refresh();setMessage('Mock A/B/C 평가 완료');})}>Mock A/B/C 평가</button></div><article><p className="muted">Test 40건 × 3개 경로. 실패도 분모에 포함합니다. Mock 결과로 실제 모델 성능 향상을 주장하지 않습니다.</p>{report?<><p>{report.id} · {report.mode.toUpperCase()}</p><table><thead><tr>{['경로','통과 / 사례','Unsafe','모델 호출','p50 / p95 (ms)'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{Object.entries(report.summary).map(([k,s])=><tr key={k}><td>{k}</td><td>{s.passed} / {s.n}</td><td>{s.unsafe}</td><td>{s.model_calls}</td><td>{s.p50_ms} / {s.p95_ms}</td></tr>)}</tbody></table></>:<p className="empty">워크플로 활성화 후 평가하세요.</p>}</article></section><footer>SkillForge · NVIDIA Agentic AI Hackathon / 합성 주문 데이터 · 로컬 데모</footer></main></>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
