import {useEffect, useState} from 'react';
type Check={expected:string;actual:string;passed:boolean;reason:string|null};
type Review={id:string;workflow_id:string;passed:boolean;applied:boolean;case_count:number;changed_count:number;unsafe_count:number;false_block_count:number;base_policy:{approval_limit_krw:number};target_policy:{approval_limit_krw:number};cases:{case_id:string;amount_krw:number;changed:boolean;before:Check;after:Check}[]};
type Flow={id:string;state:string};
type Props={flows:Flow[];busy:boolean;api:<T>(path:string,body?:unknown)=>Promise<T>;act:(fn:()=>Promise<void>)=>Promise<void>;refresh:()=>Promise<void>;message:(text:string)=>void};
const label=(value:string)=>({SUCCEEDED:'자동 환불 완료',AWAITING_APPROVAL:'운영자 승인 필요',DENIED:'환불 거절'}[value]||value);
const money=(value:number)=>value.toLocaleString('ko-KR')+'원';
export default function PolicyPanel({flows,busy,api,act,refresh,message}:Props){
 const [limit,setLimit]=useState(300000),[current,setCurrent]=useState<number|null>(null),[review,setReview]=useState<Review|null>(null);
 const active=flows.find(f=>f.state==='ACTIVE');
 useEffect(()=>{api<{approval_limit_krw:number}>('/api/policy').then(p=>setCurrent(p.approval_limit_krw)).catch(e=>message(String(e)));},[flows]);
 function download(){if(!review)return;const blob=new Blob([JSON.stringify(review,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=review.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <article className="policy-lab"><span className="eyebrow green">POLICY CHANGE LAB</span><h3>정책이 바뀌면, 무엇을 다시 확인해야 할까요?</h3><p>승인 기준 변경 전후를 같은 합성 사례로 비교합니다. 미리보기는 운영 주문을 환불하지 않습니다.</p><div className="two"><div><label htmlFor="policy-limit">새 승인 기준 (이 금액 이상은 승인 필요)</label><input id="policy-limit" type="number" min={2} max={100000000} value={limit} onChange={e=>setLimit(Number(e.target.value))}/><p>현재 기준: <strong>{current===null?'불러오는 중':money(current)}</strong></p></div><div><button className="primary wide" disabled={busy||!active||!Number.isInteger(limit)||limit<2||limit>100000000||limit===current} onClick={()=>act(async()=>{const r=await api<Review>('/api/policy/preview',{workflow_id:active!.id,approval_limit_krw:limit});setReview(r);message(`변경 영향 비교 완료: ${r.changed_count}/${r.case_count}개 사례의 처리 방식 변경`);})}>① 변경 영향 미리보기</button><p className="muted">먼저 아래에서 기록 수집 → 후보 생성 → 검증 → 활성화를 진행하세요. 비교 대상은 활성 워크플로입니다.</p></div></div>
 {review&&<><div className="metrics"><div className="metric"><b>{review.changed_count} / {review.case_count}</b><span>처리 방식이 달라진 사례</span></div><div className="metric"><b>{review.unsafe_count}</b><span>위험한 DB 변경</span></div><div className="metric"><b>{review.false_block_count}</b><span>정상 환불 오차단</span></div></div><p><strong>{money(review.base_policy.approval_limit_krw)} → {money(review.target_policy.approval_limit_krw)}</strong> · {review.passed?'비교 검사 통과':'비교 검사 실패'} · {review.applied?'정책 적용됨 · 이전 절차 재사용 중지':'미리보기 · 현재 정책 유지'}</p><table><thead><tr><th>영향 사례</th><th>환불 금액</th><th>변경 전</th><th>변경 후</th></tr></thead><tbody>{review.cases.filter(c=>c.changed).map(c=><tr key={c.case_id}><td>{c.case_id}</td><td>{money(c.amount_krw)}</td><td>{label(c.before.actual)}</td><td>{label(c.after.actual)}</td></tr>)}</tbody></table>{!review.changed_count&&<p>선택한 사례의 판정 변화가 없습니다. 정책 버전 변경 시 기존 절차는 모두 재검증합니다.</p>}<p className="muted">Validation 30개 + 이전·새 기준 경계 12개 = 42쌍의 모의 실행입니다. 실서비스 안전성 보증이나 live 모델 성능 측정이 아닙니다.</p><div className="scenarios"><button disabled={busy||review.applied||!review.passed} onClick={()=>act(async()=>{setReview(await api<Review>(`/api/policy/reviews/${review.id}/apply`,{}));await refresh();message('정책 적용 완료. 기존 절차를 STALE로 중지했습니다. 새 후보를 만들고 재검증하세요.');})}>② 확인한 정책 적용</button><button disabled={busy||!review.applied} onClick={()=>act(async()=>{await api(`/api/workflows/${review.workflow_id}/rebase`,{});await refresh();message('새 정책 후보 생성 완료. 아래 후보를 검증한 뒤 활성화하세요. 기존 출처와 이전 버전은 보존됩니다.');})}>③ 새 정책 후보 만들기</button><button onClick={download}>비교 증거 다운로드</button></div><details><summary>전체 사례와 판단 근거</summary><pre>{JSON.stringify(review,null,2)}</pre></details></>}
 </article>;
}
